//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MewToColViewWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex1table
    {
        public long id { get; set; }
        public short val1 { get; set; }
        public short val2 { get; set; }
        public short val3 { get; set; }
        public short val4 { get; set; }
        public short val5 { get; set; }
        public short val6 { get; set; }
        public short val7 { get; set; }
        public short val8 { get; set; }
        public System.DateTime time { get; set; }
    }
}
